commitizen:
  name: cz_customize
  customize:
    message_template: '{{change_type}}{% if scope %}({{scope}}){% endif %}: {{message}}'
    example: 'feature: this feature enable customize through config file'
    questions:
      - type: list
        name: change_type
        choices:
          - value: chore
            name: 'chore: commit which not trigger anything'
          - value: refactor
            name: 'refactor: a code change that neither fixes a bug nor adds a feature'
          - value: feat
            name: 'feat: a new feature'
          - value: fix
            name: 'fix: a bug fix'
          - value: style
            name: style :changes that do not affect the meaning of the code
          - value: build
            name: 'build: changes that affect the build system or external dependencies'
          - value: ci
            name: 'ci: changes to our ci configuration files and scripts'
          - value: docs
            name: 'docs: documentation only changes'
          - value: perf
            name: 'perf: a code change that improves performance'
          - value: test
            name: 'test: adding missing tests or correcting existing tests'
        message: Select the type of change you are committing
      - type: input
        name: scope
        message: 'Scope: '
      - type: input
        name: message
        message: 'Body: '
