[ids]
*

[main]
capslock = esc
esc = capslock
leftalt = layer(cmd)
leftmeta = layer(meta)

[cmd:C]
tab = swapm(app_switch, A-tab)
space = M-space

[cmd+shift]
c = cmd(copyq show)
v = cmd(copyq show)

[app_switch:A]
tab = A-tab
