-- vim.cmd.packadd('packer.nvim')
--
-- return require('packer').startup(function(use)
--   -- Packer can manage itself
--   use 'folke/tokyonight.nvim'
--   use 'lewis6991/gitsigns.nvim'
--   use 'ray-x/go.nvim'
--   use 'ray-x/guihua.lua'
--   use 'tpope/vim-fugitive'
--   use 'tpope/vim-surround'
--   use 'wbthomason/packer.nvim'
--   -- use {
--   --   'nvim-tree/nvim-tree.lua',
--   --   requires = {
--   --     'nvim-tree/nvim-web-devicons', -- optional
--   --   },
--   -- }
--   use 'editorconfig/editorconfig-vim'
--   use {
--     'VonHeikemen/lsp-zero.nvim',
--     branch = 'v2.x',
--     requires = {
--       -- LSP Support
--       {'neovim/nvim-lspconfig'},             -- Required
--       {                                      -- Optional
--         'williamboman/mason.nvim',
--         run = function()
--           pcall(vim.cmd, 'MasonUpdate')
--         end,
--       },
--       {'williamboman/mason-lspconfig.nvim'}, -- Optional
--
--       -- Autocompletion
--       {'hrsh7th/nvim-cmp'},     -- Required
--       {'hrsh7th/cmp-nvim-lsp'}, -- Required
--       {'L3MON4D3/LuaSnip'},     -- Required
--       {'google/go-cmp'},
--     }
--   }
--   use {
--       'numToStr/Comment.nvim',
--       config = function()
--           require('Comment').setup()
--       end
--   }
--   use {
-- 	  'nvim-telescope/telescope.nvim', tag = '0.1.0',
-- 	  -- or                            , branch = '0.1.x',
-- 	  requires = { {'nvim-lua/plenary.nvim'} }
--   }
--   use {
--     "cuducos/yaml.nvim",
--     ft = { "yaml" }, -- optional
--     requires = {
--       "nvim-treesitter/nvim-treesitter",
--       opts = {
--         ensure_installed = { "go", "yaml", "lua", "python", "vimdoc" },
--       },
--       "nvim-telescope/telescope.nvim" -- optional
--     },
--   }
--
-- end)
