name: PR events Slack notification
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  check-team-membership:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    outputs:
      isMember: ${{ steps.checker.outputs.permitted }}
    steps:
    - uses: TheModdingInquisition/actions-team-membership@v1.0
      id: checker
      with:
        organization: "FTAPI-Software"
        team: "operations"
        token: ${{ secrets.GET_USERGOUPS_MEMBERS_PAT }}
        exit: false
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
  collect:
    runs-on: ubuntu-latest
    if: ${{ needs.check-team-membership.outputs.isMember != 'false' }}
    needs: check-team-membership
    outputs:
      affects: ${{ steps.affects.outputs.value }}
      complexity: ${{ steps.complexity.outputs.value }}
      description: ${{ steps.description.outputs.value }}
      size_label: ${{ steps.size_label.outputs.value }}
    env:
      PR_BODY: ${{ github.event.pull_request.body }}
    steps:
      - name: Label the PR size
        uses: coverwallet/pr-labeler@v1.2.1
        with:
          xs_max_size: '5'
          s_max_size: '50'
          m_max_size: '200'
          l_max_size: '500'
          exclude_files: '.txt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: affects
        run: |
          a=$(echo -e "$PR_BODY" | grep -oP '(?<=Affects:\*\*).*' | tr -dc '[:print:]')
          echo "value=$a" >> "$GITHUB_OUTPUT"
      - id: complexity
        run: |
          c=$(echo -e "$PR_BODY" | grep -oP '(?<=Complexity:\*\*).*' | tr -dc '[:print:]')
          echo "value=$c" >> "$GITHUB_OUTPUT"
      - id: description
        run: |
          d=$(echo -e "$PR_BODY" | grep -oP '(?<=Short description:\*\*).*' | tr -dc '[:print:]')
          echo "value=$d" >> "$GITHUB_OUTPUT"
      - id: size_label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          l="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels[] | select(.name | startswith("size")) | .name')"
          echo "value=$l" >> "$GITHUB_OUTPUT"
          echo $l
  send-notification:
    runs-on: ubuntu-latest
    needs: collect
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        env:
          CREATOR_NAME: ${{ github.event.pull_request.base.user.login }}
          CREATOR_URL: ${{ github.event.pull_request.base.user.url }}
          PULL_REQUEST_AFFECTS: ${{ needs.collect.outputs.affects }}
          PULL_REQUEST_SIZE: ${{ needs.collect.outputs.size_label }}
          PULL_REQUEST_COMPLEXITY: ${{ needs.collect.outputs.complexity }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PULL_REQUEST_SHORT_DESCRIPTION: ${{ needs.collect.outputs.description }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          REPO_HTML_URL: ${{ github.event.pull_request.base.repo.html_url }}
          REPO_NAME: ${{ github.repository }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload-file-path: ./main/.github/resources/payload-slack-notification.json
