name: PR events Slack notification
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  check-team-membership:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    outputs:
      isMember: ${{ steps.checker.outputs.permitted }}
    steps:
    - uses: TheModdingInquisition/actions-team-membership@v1.0
      id: checker
      with:
        organization: "FTAPI-Software"
        team: "operations"
        token: ${{ secrets.GET_USERGOUPS_MEMBERS_PAT }}
        exit: false
  get-body:
    runs-on: ubuntu-latest
    if: ${{ needs.check-team-membership.outputs.isMember != 'false' }}
    needs: check-team-membership
    outputs:
      affects: ${{ steps.affects.outputs.value }}
      complexity: ${{ steps.complexity.outputs.value }}
      description: ${{ steps.description.outputs.value }}
    env:
      PR_BODY: ${{ github.event.pull_request.body }}
    steps:
      - id: affects
        run: |
          a=$(echo -e "$PR_BODY" | grep -oP '(?<=Affects:\*\*).*' | tr -dc '[:print:]')
          echo "value=$a" >> "$GITHUB_OUTPUT"
      - id: complexity
        run: |
          c=$(echo -e "$PR_BODY" | grep -oP '(?<=Complexity:\*\*).*' | tr -dc '[:print:]')
          echo "value=$c" >> "$GITHUB_OUTPUT"
      - id: description
        run: |
          d=$(echo -e "$PR_BODY" | grep -oP '(?<=Short description:\*\*).*' | tr -dc '[:print:]')
          echo "value=$d" >> "$GITHUB_OUTPUT"
  send-notification:
    runs-on: ubuntu-latest
    needs: get-body
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        env:
          CREATOR_NAME: ${{ github.event.pull_request.base.user.login }}
          CREATOR_URL: ${{ github.event.pull_request.base.user.url }}
          PULL_REQUEST_AFFECTS: ${{ needs.get-body.outputs.affects }}
          PULL_REQUEST_CHANGED_FILES: ${{ github.event.pull_request.changed_files }}
          PULL_REQUEST_COMPLEXITy: ${{ needs.get-body.outputs.complexity }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PULL_REQUEST_SHORT_DESCRIPTION: ${{ needs.get-body.outputs.description }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          REPO_HTML_URL: ${{ github.event.pull_request.base.repo.html_url }}
          REPO_NAME: ${{ github.repository }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload-file-path: ./main/.github/resources/payload-slack-notification.json
