name: PR creation event notification
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  get-body:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    outputs:
      affects: ${{ steps.affects.outputs.value }}
      complexity: ${{ steps.complexity.outputs.value }}
      description: ${{ steps.description.outputs.value }}
    env:
      PR_BODY: ${{ github.event.pull_request.body }}
    steps:
      - id: affects
        run: |
          a=$(echo -e "$PR_BODY" | grep -oP '(?<=Affects:).*' | tr -dc '[:print:]')
          echo "value=$a" >> "$GITHUB_OUTPUT"
      - id: complexity
        run: |
          c=$(echo -e "$PR_BODY" | grep -oP '(?<=Complexity:).*' | tr -dc '[:print:]')
          echo "value=$c" >> "$GITHUB_OUTPUT"
      - id: description
        run: |
          d=$(echo -e "$PR_BODY" | grep -oP '(?<=Description:).*' | tr -dc '[:print:]')
          echo "value=$d" >> "$GITHUB_OUTPUT"
  send-notification:
    runs-on: ubuntu-latest
    needs: get-body
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PULL_REQUESTS_PIE }}
        with:
          payload-file-path: ./.github/resources/payload-notification.json
