name: PR creation event notification
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  get-body:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    outputs:
      affects: ${{ steps.affects.outputs.value }}
      complexity: ${{ steps.complexity.outputs.value }}
      description: ${{ steps.description.outputs.value }}
    env:
      PR_BODY: ${{ github.event.pull_request.body }}
    steps:
      - id: affects
        run: |
          a=$(echo -e "$PR_BODY" | grep -oP '(?<=Affects: ).*')
          echo "value=$a" >> "$GITHUB_OUTPUT"
      - id: complexity
        run: |
          c=$(echo -e "$PR_BODY" | grep -oP '(?<=Complexity: ).*')
          echo "value=$c" >> "$GITHUB_OUTPUT"
      - id: description
        run: |
          d=$(echo -e "$PR_BODY" | grep -oP '(?<=Description: ).*')
          echo "value=$d" >> "$GITHUB_OUTPUT"
  send-notification:
    runs-on: ubuntu-latest
    needs: get-body
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          AFFECTS: ${{ needs.get-body.outputs.affects }}
          COMPLEXITY: ${{ needs.get-body.outputs.complexity }}
          DESCRIPTION: ${{ needs.get-body.outputs.description }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PULL_REQUESTS_PIE }}
        with:
          payload-file-path: "./payload-slack-content.json"
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New PR: #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project:*\n<${{ github.event.pull_request.base.repo.html_url }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Created by:\n*<${{ github.event.pull_request.base.user.url }}|${{ github.event.pull_request.base.user.login }}>*"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Filse changed:* ${{ github.event.pull_request.changed_files }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Complexity:* $COMPLEXITY"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Affects:*\$AFFECTS"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Description:*\n$DESCRIPTION"
                    }
                  ]
                },
            		{
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Open in Browser"
                      },
                      "url": "${{ github.event.pull_request.__links.html }}"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Use the following emojies as reactions to the request:\n\n"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": ":clock1: - I can look at it later (use Thread)"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":snail: - I would be able to look at it, but have no time"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":x: - I am not able to give a review, I don't know enough"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":hammer: - I'm done reviewing the PR, but I did request some changes"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":work-in-progress: - I will look at it right away"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":done: - I'm done reviewing the PR, all looks good"
                    }
                  ]
                }
              ]
            }
